* [2018-4-20 Fri] The icons are changed. Let me test it.
* [2018-4-18 Wed] OK, almost done. Next, the icons.
* [2018-4-16 Mon] Sigh, 2013 ....
As described in [[https://stackoverflow.com/questions/39475774/office-addin-fails-to-load-in-excel-2013-when-requirement-set-for-excel-api-1-2][this StackOverflow's Q&A]]
, requirement set for ~ExcelApi~ is no use for Excel 2013, I might need to check them inside the code as described [[https://docs.microsoft.com/en-us/office/dev/add-ins/develop/specify-office-hosts-and-api-requirements][here]]
** Lists of methods whose version higher than 1.1
- v1.2
  + merge
- v1.4
  + getUsedRangeOrNullObject
  + getItemOrNullObject
  + table.rows.add (multiple lines)
- v1.6
  + conditionalFormats
  + ConditionalCellValueOperator
  + ConditionalFormatType
  
* [2018-4-16 Mon] All the texts including the one in ~data-server.service~ are changed.
* [2018-4-16 Mon] Now, the pts (pageTexts) are 100% gotten from PageTextsService
* [2018-4-16 Mon] PageTexts for gen-worksheet are done

* [2018-4-13 Fri] PageTexts for Settings, both html texts and default fields' value are done.
Note, I use ~pts~ both in pageTextsService and appComponent. This might not be a good idea since they might not be coherent. 
At this moment I bind them through observable ~updateEnd~ of pageTextsService. Let me think of it. 
* [2018-4-12 Thu] The chosen pageTexts will be saved in LocalStorage
The stuff saved in LocalStorage will affect all excel documents and that it what I want because I hope that the user just need to setup the language once. To set the language for each excel document is a little wierd.
* [2018-4-11 Wed] app.component.html & welcome.component.html are multilingual now.
* [2018-4-11 Wed] Now, it can work with multilingual.
After installing ~i18n-page-texts~ 
, writing a provider ~page-texts.service.ts~
and subscribing its observable from ~app.component.ts~,
I can update its sentences with different languages.

The bash command sample is shown below.
#+begin_src sh
npm run i18n
;; do some modifications in assets/i18n/...
ng serve
#+end_src
* [2018-03-03 Sat] Submit to AppSource. 

* [2018-01-09 Tue] Install *@angular/cli*, *yo* and *@types/office-js*
  1. Following the tutorial shown in [[https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-angular][Quick Start]], [[https://docs.microsoft.com/en-us/office/dev/add-ins/develop/add-ins-with-angular2][Develop Add-in]] and [[https://docs.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins][How to sideload]]. Be careful, ~</br>~ will cause an error. It should be ~<br/>~.
  2. Well, to avoid =git= transfering =LF= to be =CRLF= which can be easily set in =VSCode=, you can fix it by adding =[core] autocrlf=false= into file /.git\/config/ to turn off this functionality. It was discussed in [[https://stackoverflow.com/questions/1967370/git-replacing-lf-with-crlf][this StackOverflow post]].
