export const defaultPTS:IPageTexts ={
  "appPage": {
    "welcome": "歡迎",
    "setup": "設定",
    "generate": "產生",
    "title": "班級成績管理小幫手"
  },
  "welcomePage": {
    "note": "注意",
    "noteIntro": "你的設定不完全，問題條列如下：",
    "notSetting": "你尚未完成任何設定",
    "noTemplateSheet": "你並沒有提供一個樣板表單",
    "noteAction": "在讀完下列說明後，請先按以下按鈕以進入設定頁面去做必要的設定，謝謝。",
    "welcomeIntro": "歡迎使用此小幫手，此小幫手可以幫你將你的學生的成績{0}依照個別的學生{1}輸出其表格，也可以看到所有學生{2}長期的學習趨勢。使用法很簡單，目前只有<b>設定</b>與<b>產生</b>這兩個功能。原始碼在{3}裡",
    "setup": "設定",
    "cSetup": "  原則上，<b>設定</b>只有在第一次使用時才需要去動用到它，因為對這個小幫手而言，它一開始並不知道你怎麼稱呼<i>ID</i>，<i>總分</i>等有特殊意義的表頭，你得在<b>設定</b>裡告訴它。此外，表單<i>{0}</i>是用來產生所有成績輸入表單的樣板，請勿刪除它，你在裏頭所新增或刪除的學生或科目，即未來你的成績輸入表單的樣板。",
    "generate": "產生",
    "cGenerate": "由這裡你可以產生每次月考成績輸入的表格，也可以產生歷年成績的比較。表單<b>{0}</b>會輸出個別學生的學習狀況，可以印下來後交給學生家長；而<b>{0}_${1}$</b>則用顏色顯示所有學生在每次考試中成績大概落在哪裡，好方便老師看出哪些學生需要輔導，而哪些又適合當小老師。",
    "eachCourse": "各科目"
  },
  "TestPage": {
    "test": "測試"
  },
  "gSettings": {
    "stID": "座號",
    "stName": "姓名",
    "stAvg": "平均",
    "stTotal": "總分",
    "stScore": "績效",
    "stTitle": "$YEAR$學年度 學期$SEM$ 第$TIMES$次考試",
    "stCAvg": "各科平均",
    "stCHighest": "最高分",
    "stCLowest": "最低分",
    "new_year": "106",
    "chartSheetName": "學生列表",
    "stSpecial": "家長簽名及意見"
  },
  "SettingsPage": {
    "special": "特殊表單名稱：",
    "pChartName": "成績圖表表單名稱：(outputs)",
    "pTmpName": "樣板表單名稱：(input)",
    "speField": "樣板表單中特殊欄位值：",
    "top": "科目上方",
    "left": "科目之左",
    "right": "科目之右",
    "bottom": "科目下方",
    "renew": "更新",
    "genTmp": "➕產生",
    "renewing": "更新中",
    "done": "完成",
    "firstTime": "第一次使用",
    "firstTimeMsg": "由於Settings尚未有任何資料，我已自動幫你產生了一份。<br/>如不滿意，請依自己的需要修改，完畢後，請按最下面的更新鈕🔃即可更新。",
    "needTmpTitle": "請先產生樣板表單",
    "needTmpMsg": "所有的成績輸入都以樣板表單為主。請先按按鈕<br/>'{0}'<br/>以自動產生一份表單給你。",
    "understand": "了解了",
    "note": "注意",
    "change": "變更",
    "unchange": "不變更",
    "keepEdit": "再修改",
    "creatingSample": "創建樣板中",
    "waiting": "請稍候",
    "running": "進行中",
    "notExisting": "工作表 {0} 不存在。<br/>",
    "settingChanged": "設定已經改變。<br/>",
    "wannaChange": "要變更嗎？"
  },
  "GenWorksheetPage": {
    "genNewSheet": "產生新表單",
    "newNameForm": "新表單名稱形式；",
    "year": "學年：",
    "sem": "學期：",
    "times": "第幾次：",
    "genNewChartSheet": "產生新圖表",
    "base": "主要",
    "compare": "比較",
    "thisTime": "這一次",
    "previousTime": "前一次",
    "chartWhichCourse": "作圖哪個成績？",
    "course": "科目",
    "chartSheetName": "輸出圖表的表單名稱",
    "output": "輸出",
    "visualize": "視覺化",
    "sen4SpecialCell": "特殊欄位文字",
    "useIt": "套用此文字",
    "tutorial": "使用以下的按鈕前，請先對表單<div class='chartSheetName'>{0}</div>裡的第一位學生的表格進行設定，如寬、高、字體、顏色等，但<br/><b>請不要刪減任何欄或行</b>",
    "justHeight": "僅套用行高",
    "forAll": "套用全部(很慢)",
    "visNote": "注意：格線其實也可套用，不過，在畫自己想要的格線前，請先將預設的所有格線洗掉後再重新開始畫格線。<br/>怎麼一次全洗掉？很簡單。只要<b>全選(Ctrl-A)</b>整個表格，然後選<b>常用=>無框線</b>即可。",
    "noGradeTitle": "沒有任何成績表單",
    "noGradeMsg": "請至少先產生並且輸入一份成績表單才能繼續你想進行的動作。",
    "gotIt": "了解了",
    "createNewSheet": "創建新表單中",
    "waiting": "請稍候",
    "failGenSheetTitle": "產生新表單失敗",
    "faliGenSheetMsg": "很可能因為表單 <em>{0}</em> 已經存在，導致你不能再造出該表單來。<br/>error: {1}",
    "running": "進行中",
    "creatingNewChart": "創建圖表中",
    "inCreating": "創建中",
    "doneNewChart": "完成創建圖表",
    "applyingFormat": "套用格式中",
    "applying": "套用中",
    "done": "完成",
    "applyingHeight": "套用行高中",
    "mayNotExistSheet": "表單 <b>{0}</b> <br/>可能不存在",
    "notExistSheet": "{0} 表單不存在",
    "applying2Student": "套用至第{0}學生"
  },
  "dataServerService": {
    "applyOnStudentCol": "完成第{0}學生的第{1}行的套用",
    "english": "英語",
    "chinese": "國文",
    "math": "數學",
    "science": "自然",
    "noTmpSheet": "表單{0}不存在，請到<b>設定</b>先創造它出來吧。",
    "start": "開始",
    "timesID": "成績表單➡\nID⬇",
    "compare": "比較: {0}",
    "output2IDDone": "輸出ID={0} 完成",
    "noSheet": "{0} 不存在，請先產生它",
    "completeIthStu": "完成第{0}位成績",
    "applyingOnRow": "套用第{0}行中"
  }
}